### ISSUE TITLE
About the Color augmentation details

### ISSUE THREAD

**Issue by stardusts-hj** [madebyollin/taesd#21]
Hi madebyollin!
Thanks for sharing this wonderful work! I find taesd really useful and I'm trying to finetune the pretrained taesd.
I also observed the shift of color in reconstructed images without color augmentation. So I would like to ask you for the details of the color augmentation strategy used in taesd training.
![20240626-114132](https://github.com/madebyollin/taesd/assets/54565340/dd849d58-6cae-42c9-b8d0-0a4771477c48)

Thanks!

**Comment by madebyollin** [comment]
Nothing particularly exciting - this is the code I used (assuming [0, 1] images, applied to 5-10% of samples)
```python
def color_augment(im):
    scale = 0.5 + th.randn(3, 3)
    blend = th.rand(3, 1, 1)
    return (scale @ im.flatten(1)).view(im.shape).clamp(0, 1) * blend + (1 - blend) * im
```

**Comment by stardusts-hj** [comment]
Thanks for your kind reply!
