### ISSUE TITLE
Datasets for training your TinyEncoder

### ISSUE THREAD

**Issue by eladc-git** [madebyollin/taesd#27]
Hi, 
thanks for the great work.

I wonder,  what datasets do you use to train your encoders?
 
Elad

**Comment by madebyollin** [comment]
https://huggingface.co/datasets/madebyollin/megalith-10m for photos, of course :) but I've usually mixed in subsets of laion (lots of product images / web graphics) and danbooru (lots of illustrations) to try and cover all bases.
