### ISSUE TITLE
weights for x4 upscaler

### ISSUE THREAD

**Issue by keturn** [madebyollin/taesd#4]
This is a wonderful project!

What would be involved in getting TAESD for the [Stable Diffusion x4 upscaler](https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler)?

It uses a different VAE than the other Stable Diffusion models.

**Comment by madebyollin** [comment]
Hmm, it looks like this VAE is `f/4` instead of `f/8`, so I'd need to modify the TAESD arch slightly (and retrain a new set of weights)...

**Comment by madebyollin** [comment]
Added a `stable-diffusion-x4-upscaler`-compatible TAESD variant here https://huggingface.co/madebyollin/taesd-x4-upscaler.

**Original image:**
![image](https://github.com/madebyollin/taesd/assets/8733615/dd7901fc-7a37-4b1b-ac8e-8460207e8b87)

| TAESD-X4-Upscaler | SD-X4-Upscaler VAE |
| ----------------- | ------------------ |
| ![preview_images](https://github.com/madebyollin/taesd/assets/8733615/226b4c72-a473-453d-a6a6-19cb37cfa15f) | ![preview_images_orig](https://github.com/madebyollin/taesd/assets/8733615/0241f617-b8a4-4d9a-b953-054af1df659f) |
| ![image](https://github.com/madebyollin/taesd/assets/8733615/4299fb1d-4bb0-4383-9650-cb1b4470866f) | ![image](https://github.com/madebyollin/taesd/assets/8733615/0c50073d-aa1f-4bba-9d64-937cecca7eff) |

**Comment by keturn** [comment]
Thanks, I look forward to trying that out soon!
