### ISSUE TITLE
Preview for discrete schedulers?

### ISSUE THREAD

**Issue by skirsten** [madebyollin/taesd#5]
Hi, I am trying to generate preview images using something similar to https://github.com/madebyollin/taesd/blob/main/examples/Previewing_During_Image_Generation.ipynb.

```
alphas_cumprod = pipe.scheduler.alphas_cumprod.to(t.device)
alpha_prod_t = alphas_cumprod[int(t)]

pred_original_sample = (latents - (1 - alpha_prod_t) ** 0.5 * noise_pred) / alpha_prod_t**0.5
```

Unfortunately the formula from this notebook does not work well in the beginning of the discrete schedulers.
### DDIMScheduler
![DDIMScheduler webp](https://github.com/huggingface/diffusers/assets/1972314/41f5e99e-f7d6-417e-b671-d5bc92805644)
### DDPMScheduler
![DDPMScheduler webp](https://github.com/huggingface/diffusers/assets/1972314/e6528242-1e5e-4de4-a191-70d9f0df96ef)
### DPMSolverMultistepScheduler
![DPMSolverMultistepScheduler webp](https://github.com/huggingface/diffusers/assets/1972314/cebd9cc4-06c7-4963-81d1-2aa97d14d034)
### PNDMScheduler
![PNDMScheduler webp](https://github.com/huggingface/diffusers/assets/1972314/de0bcb36-2d8c-4391-82a2-f28ffaf2684a)

### EulerAncestralDiscreteScheduler
![EulerAncestralDiscreteScheduler webp](https://github.com/huggingface/diffusers/assets/1972314/2cca4c49-c82a-4998-be32-e9a491a9c9b5)
### EulerDiscreteScheduler
![EulerDiscreteScheduler webp](https://github.com/huggingface/diffusers/assets/1972314/9e7dac17-dc49-4155-bc82-ff42d20312ef)
### LMSDiscreteScheduler
![LMSDiscreteScheduler webp](https://github.com/huggingface/diffusers/assets/1972314/2f7557fa-9cb2-41ad-ad9f-ae4d5540ecbf)

I also posted this [on a diffusers issue](https://github.com/huggingface/diffusers/issues/3579) but also wanted to ask here, as this is where I got the formula from.

I know this is not really related with taesd but any help is appreciated!

**Comment by madebyollin** [comment]
Try this:
```python
def get_pred_original_sample(sched, model_output, timestep, sample):
    return sample - sched.sigmas[(sched.timesteps == timestep).nonzero().item()] * model_output
```
Test gif with `EulerAncestralDiscreteScheduler`:

![preview_images](https://github.com/madebyollin/taesd/assets/8733615/f8a7e064-c3be-4326-a62a-c4a8a4aad39f)


(For future reference, the correct `pred_original_sample` expressions are hidden [inside the corresponding scheduler code](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_euler_discrete.py#L385))

**Comment by skirsten** [comment]
Thank you so much for pointing me in this direction. I actually tried to find the formula in the diffusers codebase but I looked in the DPMSolverMultistepScheduler which does not have it :).

> Oh, and also, for some schedulers, if you override kwargs['return_dict'] = True you can just use res.pred_original_sample and don't need get_pred_original_sample at all :P)

I had the same idea after checking the scheduler code you linked :+1: , here is the code I use now:
```py
orig_step = pipe.scheduler.step

def step(model_output, timestep, sample, *args, **kwargs):
    return_dict = kwargs.get("return_dict", True)
    kwargs["return_dict"] = True

    output = orig_step(model_output, timestep, sample, *args, **kwargs)

    images = pipe.vae.decode(output.pred_original_sample / pipe.vae.config.scaling_factor)[0]

    preview_image = pipe.image_processor.postprocess(images)

    preview_images.append(preview_image[0])

    if not return_dict:
        return (output[0],)

    return output


pipe.scheduler.step = step
```

Unfortunately it does not work for `DPMSolverMultistepScheduler` and `PNDMScheduler` but the rest I listed above work.
Thank you again so much :smile:

**Comment by gabgren** [comment]
> Try this:
> 
> ```python
> def get_pred_original_sample(sched, model_output, timestep, sample):
>     return sample - sched.sigmas[(sched.timesteps == timestep).nonzero().item()] * model_output
> ```
> 
> Test gif with `EulerAncestralDiscreteScheduler`:
> 
> ![preview_images](https://user-images.githubusercontent.com/8733615/258617323-f8a7e064-c3be-4326-a62a-c4a8a4aad39f.gif) [ ![preview_images](https://user-images.githubusercontent.com/8733615/258617323-f8a7e064-c3be-4326-a62a-c4a8a4aad39f.gif) ](https://user-images.githubusercontent.com/8733615/258617323-f8a7e064-c3be-4326-a62a-c4a8a4aad39f.gif) [ ](https://user-images.githubusercontent.com/8733615/258617323-f8a7e064-c3be-4326-a62a-c4a8a4aad39f.gif)
> 
> (For future reference, the correct `pred_original_sample` expressions are usually hidden [inside the corresponding scheduler code](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py#L296). **EDIT:** Oh, and also, for some schedulers, if you override `kwargs['return_dict'] = True` you can just use `res.pred_original_sample` and don't need `get_pred_original_sample` at all :P)

Hi,

Do you know how to implement this in diffusers pipeline? is it in the callback() from the pipeline call, or elsewhere?

**Comment by madebyollin** [comment]
@gabgren By "this" do you mean "live previewing"? Live previewing with diffusers is demonstrated in the [example notebook](https://github.com/madebyollin/taesd/blob/main/examples/Previewing_During_Image_Generation.ipynb). When I [checked](https://github.com/huggingface/diffusers/issues/3579#issuecomment-1666696736) it seemed like live previewing can't be done with callbacks alone, because `pred_original_sample` is not accessible from callbacks.
