### ISSUE TITLE
FR: safetensors version?

### ISSUE THREAD

**Issue by Aptronymist** [madebyollin/taesd#6]
Is there any chance you could put up a version that's converted to .safetensors so it could be easily used as a full VAE?
I was hoping to put it to use for precisely that, as it does such a wonderful job making previews!

Thank you for making it!

**Comment by madebyollin** [comment]
Diffusers-compatible `safetensors` versions are here
* https://huggingface.co/madebyollin/taesd
* https://huggingface.co/madebyollin/taesdxl

(TODO - add these links to the README in this repo)

**Comment by Aptronymist** [comment]
> Diffusers-compatible `safetensors` versions are here
> 
> * [huggingface.co/madebyollin/taesd](https://huggingface.co/madebyollin/taesd)
> * [huggingface.co/madebyollin/taesdxl](https://huggingface.co/madebyollin/taesdxl)
> 
> (TODO - add these links to the README in this repo)

Oh, wonderful, thank you!
