### ISSUE TITLE
How to install or is there not a visible section for it in Auto1111?

### ISSUE THREAD

**Issue by XeroCreator** [madebyollin/taesd#7]
I've only been using Auto1111 and SD for a little over a week, I tried to install this via the extensions tab and the 'install from link' but nothing seems to have changed so i am thinking that must not be the way to install it?
Or perhaps i'm misunderstanding what this is actually doing or where it is supposed to show up?

I have no problem writing an install guide and a how to use guide after I get it working.

thanks :)

**Comment by madebyollin** [comment]
TAESD previewing is already built in :) just need to enable it in A1111 settings

![image](https://github.com/madebyollin/taesd/assets/8733615/32ccb0df-bb8e-4392-b445-80e469b3be7e)

Demo video:
![](https://github.com/madebyollin/taesd/assets/8733615/f306741e-0baa-4d80-a3f6-ee0202666eb1)
